# Generated by Django 4.1.5 on 2023-01-12 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='child',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=64, null=True)),
                ('Last_name', models.CharField(max_length=64, null=True)),
                ('Gender', models.CharField(max_length=64, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('Organization', models.CharField(max_length=64, null=True)),
                ('Father_name', models.CharField(max_length=64, null=True)),
                ('Father_mobile', models.CharField(max_length=64, null=True)),
                ('Mother_name', models.CharField(max_length=64, null=True)),
                ('State', models.CharField(max_length=64, null=True)),
                ('District', models.CharField(max_length=64, null=True)),
                ('Taluk', models.CharField(max_length=64, null=True)),
                ('Village', models.CharField(max_length=64, null=True)),
                ('User_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(null=True)),
                ('Manual_height', models.CharField(max_length=64, null=True)),
                ('Manual_weight', models.CharField(max_length=64, null=True)),
                ('child_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='APP.child')),
            ],
        ),
        migrations.CreateModel(
            name='auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(null=True)),
                ('Auto_height', models.CharField(max_length=64, null=True)),
                ('Auto_weight', models.CharField(max_length=64, null=True)),
                ('child_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='APP.child')),
            ],
        ),
    ]
