# Generated by Django 4.1.5 on 2023-01-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='child_id',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='User_id',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='manual',
            name='child_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
