# Generated by Django 4.1.5 on 2023-01-13 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('APP', '0002_alter_auto_child_id_alter_child_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='child_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='APP.child'),
        ),
        migrations.AlterField(
            model_name='child',
            name='User_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manual',
            name='child_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='APP.child'),
        ),
    ]
