# Generated by Django 4.1.5 on 2023-01-15 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_rename_id_child_child_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='child_id',
            new_name='id',
        ),
    ]
