# Generated by Django 4.1.5 on 2023-01-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_rename_child_id_child_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(null=True)),
                ('age', models.CharField(max_length=64, null=True)),
                ('Auto_height', models.CharField(max_length=64, null=True)),
                ('Auto_weight', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
