# Generated by Django 4.1.5 on 2023-01-31 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_chart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Auto_height', models.TextField()),
                ('Auto_weight', models.TextField()),
                ('child_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='APP.child')),
            ],
        ),
        migrations.RemoveField(
            model_name='auto',
            name='child_id',
        ),
        migrations.DeleteModel(
            name='chart',
        ),
        migrations.DeleteModel(
            name='auto',
        ),
    ]
