# Generated by Django 4.1.5 on 2023-01-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_auto_data_remove_auto_child_id_delete_chart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto_data',
            name='Date',
            field=models.TextField(),
        ),
    ]
