# Generated by Django 4.1.5 on 2023-01-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0008_alter_auto_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto_data',
            name='Date',
            field=models.DateField(),
        ),
    ]
