# Generated by Django 4.1.5 on 2023-01-31 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0009_alter_auto_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto_data',
            name='child_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.child'),
        ),
    ]
